version: '3.8'
services:
  front: 
    build:
      context: $PWD/front
      dockerfile: Dockerfile
    volumes:
      - $PWD/front:/app:rw
  proxy:
    build:
      dockerfile: $PWD/dockerfiles/proxyprod.Dockerfile
      context: $PWD/dockerfiles/
    image: docker.io/nginx:alpine
    env_file: .env
    depends_on:
      - php_fpm
      - db
      - front
    volumes:
      - $PWD:/var/www/html:rw
      # - $PWD/dockerfiles/production/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - front
      - socket
    ports:
      # - 8000:8000/tcp
      - 443:443/tcp
  db:
    image: docker.io/mysql:8.0
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    volumes:
      - $PWD/mycustom.cnf:/etc/mysql/conf.d/custom.cnf
      - db_data:/var/lib/mysql
  php_fpm:
    build:
      dockerfile: $PWD/dockerfiles/php-fpm.Dockerfile
      context: $PWD/dockerfiles/
    volumes:
      - $PWD:/var/www/html:rw
      - $PWD/dockerfiles/local.ini:/usr/local/etc/php/conf.d/local.ini
      - $PWD/dockerfiles/php.ini:/usr/local/etc/php/php.ini
volumes:
  db_data:
    driver: local
