version: '3.8'
services:
  proxy:
    build:
      dockerfile: $PWD/dockerfiles/proxy.Dockerfile
      context: $PWD/dockerfiles/nginx/
    env_file: .env
    depends_on:
      - php_fpm
      - db
    volumes:
      - $PWD:/var/www/html:rw
      - $PWD/dockerfiles/nginx/nginx.conf:/etc/nginx/nginx.conf:rw
    ports:
      - 8003:80/tcp
  db:
    image: docker.io/mysql:8.0
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    volumes:
      - $PWD/mycustom.cnf:/etc/mysql/conf.d/custom.cnf
      - db_data:/var/lib/mysql
  php_fpm:
    build:
      dockerfile: $PWD/dockerfiles/php-fpm.Dockerfile
      context: $PWD/dockerfiles/
    volumes:
      - $PWD:/var/www/html:rw
      - $PWD/dockerfiles/php.ini:/usr/local/etc/php/conf.d/local.ini
  adminer:
    image: docker.io/adminer:latest
    ports:
      - 8081:8080/tcp
volumes:
  db_data:
    driver: local
